const express = require('express')
const crypto = require('crypto')
const PDFDocument = require('pdfkit')

const id = () => crypto.randomUUID()

function createCrudRoutes({ db, auth, requireRole, requirePermission, audit }) {
  const router = express.Router()
  const writeRoles = ['ADMINISTRADOR', 'DIRETOR', 'GERENTE', 'SUPERVISOR']
  const financeRoles = [...writeRoles, 'FINANCEIRO']
  const supplyRoles = [...writeRoles, 'COMPRAS', 'ESTOQUE']
  const commercialRoles = [...writeRoles, 'COMERCIAL']

  const paginationFor = (request) => {
    const requestedPage = Number.parseInt(request.query.page, 10)
    const requestedPageSize = Number.parseInt(request.query.pageSize, 10)
    const page = Number.isFinite(requestedPage) ? Math.max(1, requestedPage) : 1
    const pageSize = Number.isFinite(requestedPageSize) ? Math.min(100, Math.max(1, requestedPageSize)) : 20
    return { page, pageSize, offset: (page - 1) * pageSize, requested: request.query.page !== undefined || request.query.pageSize !== undefined }
  }

  const sortFor = (request, fields) => ({ field: fields.includes(request.query.sort) ? request.query.sort : 'created_at', direction: request.query.direction === 'asc' ? 'ASC' : 'DESC' })

  const resources = {
    products: { table: 'products', fields: ['sku', 'name', 'category', 'unit', 'min_stock', 'max_stock', 'cost_unit', 'supplier_id'], required: ['name'], roles: supplyRoles },
    categories: { table: 'product_categories', fields: ['name', 'parent_id'], required: ['name'], roles: supplyRoles },
    'storage-locations': { table: 'storage_locations', fields: ['name', 'address'], required: ['name'], roles: supplyRoles },
    suppliers: { table: 'suppliers', fields: ['legal_name', 'trade_name', 'document', 'state_registration', 'email', 'phone', 'zip_code', 'address', 'address_number', 'complement', 'district', 'city', 'state', 'contact_name', 'category', 'payment_terms', 'bank', 'bank_branch', 'bank_account', 'pix_key', 'notes', 'archived'], required: ['legal_name'], roles: supplyRoles },
    equipment: { table: 'equipment', fields: ['code', 'name', 'type', 'brand', 'model', 'serial_number', 'year', 'acquisition_date', 'value', 'location', 'project_id', 'responsible', 'horometer', 'mileage', 'status', 'notes'], required: ['code', 'name'], roles: writeRoles },
    'accounts-payable': { table: 'accounts_payable', fields: ['supplier_id', 'project_id', 'category', 'cost_center', 'description', 'document_number', 'issue_date', 'competence', 'due_date', 'amount', 'discount', 'interest', 'fine', 'payment_method', 'bank_account', 'observations', 'status'], required: ['description', 'due_date', 'amount'], roles: financeRoles },
    'accounts-receivable': { table: 'accounts_receivable', fields: ['client_id', 'project_id', 'category', 'revenue_center', 'description', 'document_number', 'issue_date', 'competence', 'due_date', 'amount', 'discount', 'interest', 'receipt_method', 'bank_account', 'observations', 'status'], required: ['description', 'due_date', 'amount'], roles: financeRoles },
    transactions: { table: 'financial_transactions', fields: ['project_id', 'description', 'category', 'cost_center', 'amount', 'type', 'status', 'transaction_date'], required: ['description', 'amount', 'type', 'transaction_date'], roles: financeRoles },
    'cost-centers': { table: 'cost_centers', fields: ['name'], required: ['name'], roles: financeRoles },
    'purchase-requests': { table: 'purchase_requests', fields: ['number', 'project_id', 'requester_id', 'cost_center', 'priority', 'requested_date', 'needed_date', 'justification', 'observations', 'status'], required: ['justification'], roles: supplyRoles },
    quotations: { table: 'quotations', fields: ['purchase_request_id', 'supplier_id', 'unit_price', 'freight', 'delivery_days', 'payment_terms', 'valid_until', 'total', 'status'], required: ['purchase_request_id', 'supplier_id'], roles: supplyRoles },
    'purchase-orders': { table: 'purchase_orders', fields: ['supplier_id', 'project_id', 'status', 'total'], required: [], roles: supplyRoles },
    contracts: { table: 'contracts', fields: ['project_id', 'client_id', 'number', 'amount', 'starts_at', 'ends_at', 'status'], required: ['number'], roles: commercialRoles },
    budgets: { table: 'budgets', fields: ['client_id', 'project_id', 'number', 'total', 'status'], required: ['number'], roles: commercialRoles },
    'field-activities': { table: 'field_activities', fields: ['project_id', 'client_id', 'title', 'type', 'responsible', 'starts_at', 'ends_at', 'location', 'participants', 'description', 'status'], required: ['title'], roles: writeRoles },
    documents: { table: 'documents', fields: ['name', 'category', 'path', 'version'], required: ['name'], roles: writeRoles },
    notifications: { table: 'notifications', fields: ['user_id', 'title', 'body', 'read_at'], required: ['title'], roles: writeRoles },
  }

  function valuesFor(config, body) { const defaults = { unit: 'UN', min_stock: 0, max_stock: null, cost_unit: 0, archived: 0, discount: 0, interest: 0, fine: 0, labor_cost: 0 }; const statusDefaults = { accounts_payable: 'PENDENTE', accounts_receivable: 'PENDENTE', purchase_requests: 'ABERTA', quotations: 'ABERTA', purchase_orders: 'ABERTA', equipment: 'DISPONIVEL', field_activities: 'AGENDADA', contracts: 'ATIVO', budgets: 'RASCUNHO' }; return config.fields.map((field) => body[field] ?? (field === 'status' ? statusDefaults[config.table] : defaults[field] ?? null)) }
  const permissionFor = (name) => ({ products: 'inventory', categories: 'inventory', 'storage-locations': 'inventory', suppliers: 'suppliers', equipment: 'equipment', 'accounts-payable': 'finance', 'accounts-receivable': 'finance', transactions: 'finance', 'cost-centers': 'finance', 'purchase-requests': 'purchases', quotations: 'quotations', 'purchase-orders': 'purchases', contracts: 'projects', budgets: 'projects', 'field-activities': 'agenda', documents: 'documents', notifications: 'dashboard' }[name] || name)
  function mountResource(name, config) {
    const base = `/api/${name}`
    const permission = permissionFor(name)
    const buildQuery = (request) => { const search = String(request.query.search || ''); const params = [request.user.company_id]; const where = ['company_id = ?']; if (config.table === 'suppliers' || config.table === 'documents' && request.query.archived !== '1') where.push('archived = 0'); if (request.query.category && config.fields.includes('category')) { where.push('category = ?'); params.push(request.query.category) } if (request.query.city && config.fields.includes('city')) { where.push('city = ?'); params.push(request.query.city) } if (request.query.type && config.fields.includes('type')) { where.push('type = ?'); params.push(request.query.type) } if (request.query.status && config.fields.includes('status')) { where.push('status = ?'); params.push(request.query.status) } if (request.query.project_id && config.fields.includes('project_id')) { where.push('project_id = ?'); params.push(request.query.project_id) } if (request.query.supplier_id && config.fields.includes('supplier_id')) { where.push('supplier_id = ?'); params.push(request.query.supplier_id) } if (request.query.purchase_request_id && config.fields.includes('purchase_request_id')) { where.push('purchase_request_id = ?'); params.push(request.query.purchase_request_id) } if (request.query.related_entity && config.fields.includes('related_entity')) { where.push('related_entity = ?'); params.push(request.query.related_entity) } if (request.query.related_id && config.fields.includes('related_id')) { where.push('related_id = ?'); params.push(request.query.related_id) } if (request.query.from) { where.push('date(created_at) >= date(?)'); params.push(request.query.from) } if (request.query.to) { where.push('date(created_at) <= date(?)'); params.push(request.query.to) } if (search) { const searchable = config.fields.filter((field) => ['name', 'legal_name', 'trade_name', 'description', 'title', 'code', 'document', 'email', 'category', 'type', 'number'].includes(field)); if (searchable.length) { where.push(`(${searchable.map((field) => `${field} LIKE ?`).join(' OR ')})`); params.push(...searchable.map(() => `%${search}%`)) } } return { where, params } }
    router.get(`${base}/export`, auth, requireRole('ADMINISTRADOR', 'DIRETOR', 'GERENTE', 'FINANCEIRO', 'COMPRAS', 'ESTOQUE', 'COMERCIAL'), async (request, response) => { try { const { where, params } = buildQuery(request); const rows = await db.all(`SELECT * FROM ${config.table} WHERE ${where.join(' AND ')} ORDER BY created_at DESC`, params); const format = String(request.query.format || 'csv').toLowerCase(); const columns = rows.length ? Object.keys(rows[0]) : config.fields; if (format === 'csv') { const csv = [columns.join(','), ...rows.map((row) => columns.map((column) => JSON.stringify(row[column] ?? '')).join(','))].join('\n'); response.type('text/csv').attachment(`${name}.csv`).send(csv); return } if (format === 'xlsx') { const escapeHtml = (value) => String(value ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'); const html = `<table><thead><tr>${columns.map((column) => `<th>${escapeHtml(column)}</th>`).join('')}</tr></thead><tbody>${rows.map((row) => `<tr>${columns.map((column) => `<td>${escapeHtml(row[column])}</td>`).join('')}</tr>`).join('')}</tbody></table>`; response.type('application/vnd.ms-excel').attachment(`${name}.xls`).send(html); return } const document = new PDFDocument({ margin: 36 }); response.type('application/pdf').attachment(`${name}.pdf`); document.pipe(response); document.fontSize(16).text(`Nexora - ${name}`, { underline: true }); document.moveDown(); rows.forEach((row) => { document.fontSize(9).text(Object.entries(row).map(([key, value]) => `${key}: ${value ?? ''}`).join(' | ')); document.moveDown(0.4) }); document.end() } catch (error) { response.status(500).json({ error: 'Não foi possível exportar os registros.' }) } })
    router.get(base, auth, async (request, response) => { try { const { where, params } = buildQuery(request); const sortFields = [...config.fields, 'created_at', 'updated_at']; const { field, direction } = sortFor(request, sortFields); const pagination = paginationFor(request); const count = await db.get(`SELECT COUNT(*) AS total FROM ${config.table} WHERE ${where.join(' AND ')}`, params); const rows = await db.all(`SELECT * FROM ${config.table} WHERE ${where.join(' AND ')} ORDER BY ${field} ${direction} LIMIT ? OFFSET ?`, [...params, pagination.pageSize, pagination.offset]); response.json(pagination.requested ? { data: rows, pagination: { page: pagination.page, pageSize: pagination.pageSize, total: count.total, totalPages: Math.ceil(count.total / pagination.pageSize) } } : rows) } catch (error) { response.status(500).json({ error: 'Não foi possível listar os registros.' }) } })
    router.post(base, auth, requireRole(...config.roles), async (request, response) => { try { const missing = config.required.find((field) => request.body[field] === undefined || request.body[field] === ''); if (missing) return response.status(400).json({ error: `O campo ${missing} é obrigatório.` }); const recordId = id(); const fields = ['id', 'company_id', ...config.fields]; const values = [recordId, request.user.company_id, ...valuesFor(config, request.body)]; await db.run(`INSERT INTO ${config.table} (${fields.join(', ')}) VALUES (${fields.map(() => '?').join(', ')})`, values); const created = await db.get(`SELECT * FROM ${config.table} WHERE id = ? AND company_id = ?`, [recordId, request.user.company_id]); await audit(request.user, 'CRIAR', name.toUpperCase(), recordId, null, created); response.status(201).json(created) } catch (error) { console.error(`CRUD create ${name}`, error); response.status(500).json({ error: 'Não foi possível criar o registro.' }) } })
    router.get(`${base}/:id`, auth, async (request, response) => { try { const record = await db.get(`SELECT * FROM ${config.table} WHERE id = ? AND company_id = ?`, [request.params.id, request.user.company_id]); if (!record) return response.status(404).json({ error: 'Registro não encontrado.' }); response.json(record) } catch (error) { response.status(500).json({ error: 'Não foi possível consultar o registro.' }) } })
    router.put(`${base}/:id`, auth, requireRole(...config.roles), async (request, response) => { try { const previous = await db.get(`SELECT * FROM ${config.table} WHERE id = ? AND company_id = ?`, [request.params.id, request.user.company_id]); if (!previous) return response.status(404).json({ error: 'Registro não encontrado.' }); const updates = config.fields.map((field) => `${field} = ?`).join(', '); await db.run(`UPDATE ${config.table} SET ${updates}, updated_at = CURRENT_TIMESTAMP WHERE id = ? AND company_id = ?`, [...valuesFor(config, request.body), request.params.id, request.user.company_id]); const updated = await db.get(`SELECT * FROM ${config.table} WHERE id = ? AND company_id = ?`, [request.params.id, request.user.company_id]); await audit(request.user, 'EDITAR', name.toUpperCase(), request.params.id, previous, updated); response.json(updated) } catch (error) { response.status(500).json({ error: 'Não foi possível editar o registro.' }) } })
    router.delete(`${base}/:id`, auth, requireRole(...config.roles), async (request, response) => { try { const previous = await db.get(`SELECT * FROM ${config.table} WHERE id = ? AND company_id = ?`, [request.params.id, request.user.company_id]); if (!previous) return response.status(404).json({ error: 'Registro não encontrado.' }); await db.run(`DELETE FROM ${config.table} WHERE id = ? AND company_id = ?`, [request.params.id, request.user.company_id]); await audit(request.user, 'EXCLUIR', name.toUpperCase(), request.params.id, previous, null); response.status(204).end() } catch (error) { response.status(500).json({ error: 'Não foi possível excluir o registro.' }) } })
  }
  Object.entries(resources).forEach(([name, config]) => mountResource(name, config))
  router.post('/api/suppliers/:id/archive', auth, requireRole(...supplyRoles), async (request, response) => { try { const supplier = await db.get('SELECT * FROM suppliers WHERE id = ? AND company_id = ?', [request.params.id, request.user.company_id]); if (!supplier) return response.status(404).json({ error: 'Fornecedor não encontrado.' }); await db.run('UPDATE suppliers SET archived = 1, updated_at = CURRENT_TIMESTAMP WHERE id = ? AND company_id = ?', [supplier.id, request.user.company_id]); await audit(request.user, 'ARQUIVAR', 'FORNECEDORES', supplier.id, supplier, { ...supplier, archived: 1 }); response.json({ ok: true }) } catch (error) { response.status(500).json({ error: 'Não foi possível arquivar o fornecedor.' }) } })

  router.get('/api/inventory', auth, async (request, response) => { try { const pagination = paginationFor(request); const params = [request.user.company_id]; const where = ['i.company_id = ?']; if (request.query.search) { where.push('(p.name LIKE ? OR p.sku LIKE ?)'); params.push(`%${request.query.search}%`, `%${request.query.search}%`) } const sort = request.query.sort === 'product_name' ? 'p.name' : request.query.sort === 'quantity' ? 'i.quantity' : 'i.updated_at'; const direction = request.query.direction === 'asc' ? 'ASC' : 'DESC'; const count = await db.get(`SELECT COUNT(*) AS total FROM inventory i JOIN products p ON p.id = i.product_id WHERE ${where.join(' AND ')}`, params); const rows = await db.all(`SELECT i.*, p.name AS product_name, p.sku FROM inventory i JOIN products p ON p.id = i.product_id WHERE ${where.join(' AND ')} ORDER BY ${sort} ${direction} LIMIT ? OFFSET ?`, [...params, pagination.pageSize, pagination.offset]); response.json(pagination.requested ? { data: rows, pagination: { page: pagination.page, pageSize: pagination.pageSize, total: count.total, totalPages: Math.ceil(count.total / pagination.pageSize) } } : rows) } catch (error) { response.status(500).json({ error: 'Não foi possível listar o estoque.' }) } })
  router.get('/api/inventory/movements', auth, async (request, response) => { try { const pagination = paginationFor(request); const params = [request.user.company_id]; const where = ['m.company_id = ?']; if (request.query.search) { where.push('(p.name LIKE ? OR p.sku LIKE ?)'); params.push(`%${request.query.search}%`, `%${request.query.search}%`) } if (request.query.type) { where.push('m.type = ?'); params.push(request.query.type) } if (request.query.from) { where.push('date(m.created_at) >= date(?)'); params.push(request.query.from) } if (request.query.to) { where.push('date(m.created_at) <= date(?)'); params.push(request.query.to) } const sort = request.query.sort === 'quantity' ? 'm.quantity' : 'm.created_at'; const direction = request.query.direction === 'asc' ? 'ASC' : 'DESC'; const count = await db.get(`SELECT COUNT(*) AS total FROM inventory_movements m JOIN products p ON p.id = m.product_id WHERE ${where.join(' AND ')}`, params); const rows = await db.all(`SELECT m.*, p.name AS product_name FROM inventory_movements m JOIN products p ON p.id = m.product_id WHERE ${where.join(' AND ')} ORDER BY ${sort} ${direction} LIMIT ? OFFSET ?`, [...params, pagination.pageSize, pagination.offset]); response.json(pagination.requested ? { data: rows, pagination: { page: pagination.page, pageSize: pagination.pageSize, total: count.total, totalPages: Math.ceil(count.total / pagination.pageSize) } } : rows) } catch (error) { response.status(500).json({ error: 'Não foi possível listar as movimentações.' }) } })
  router.get('/api/inventory/reservations', auth, async (request, response) => { try { response.json(await db.all('SELECT r.*, p.name AS product_name, pr.name AS project_name FROM inventory_reservations r JOIN products p ON p.id = r.product_id JOIN projects pr ON pr.id = r.project_id WHERE r.company_id = ? ORDER BY r.created_at DESC', [request.user.company_id])) } catch (error) { response.status(500).json({ error: 'Não foi possível listar as reservas.' }) } })
  router.post('/api/inventory/movements', auth, requireRole(...supplyRoles), async (request, response) => { const { product_id: productId, project_id: projectId, type, quantity, note } = request.body; const amount = Number(quantity); if (!productId || !['ENTRADA', 'SAIDA', 'AJUSTE', 'TRANSFERENCIA'].includes(type) || !Number.isFinite(amount) || amount <= 0) return response.status(400).json({ error: 'Produto, tipo e quantidade válida são obrigatórios.' }); try { const existing = await db.get('SELECT * FROM inventory WHERE company_id = ? AND product_id = ? AND COALESCE(project_id, "") = COALESCE(?, "")', [request.user.company_id, productId, projectId || null]); const current = existing?.quantity || 0; const next = type === 'SAIDA' ? current - amount : type === 'AJUSTE' ? amount : current + amount; if (next < 0) return response.status(409).json({ error: 'Saldo insuficiente para esta saída.' }); const movementId = id(); await db.transaction(async () => { if (existing) await db.run('UPDATE inventory SET quantity = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? AND company_id = ?', [next, existing.id, request.user.company_id]); else await db.run('INSERT INTO inventory (id, company_id, product_id, project_id, quantity) VALUES (?, ?, ?, ?, ?)', [id(), request.user.company_id, productId, projectId || null, next]); await db.run('INSERT INTO inventory_movements (id, company_id, product_id, project_id, type, quantity, user_id, note) VALUES (?, ?, ?, ?, ?, ?, ?, ?)', [movementId, request.user.company_id, productId, projectId || null, type, amount, request.user.id, note || null]); }); await audit(request.user, type, 'ESTOQUE', movementId, { quantity: current }, { quantity: next }); response.status(201).json({ id: movementId, balance: next }) } catch (error) { response.status(500).json({ error: 'Não foi possível registrar a movimentação.' }) } })
  router.post('/api/inventory/reservations', auth, requireRole(...supplyRoles), async (request, response) => { const { product_id: productId, project_id: projectId, quantity } = request.body; const amount = Number(quantity); if (!productId || !projectId || !Number.isFinite(amount) || amount <= 0) return response.status(400).json({ error: 'Produto, obra e quantidade são obrigatórios.' }); try { const stock = await db.get('SELECT * FROM inventory WHERE company_id = ? AND product_id = ?', [request.user.company_id, productId]); if (!stock || stock.quantity - stock.reserved_quantity < amount) return response.status(409).json({ error: 'Saldo disponível insuficiente para reserva.' }); const reservationId = id(); await db.transaction(async () => { await db.run('UPDATE inventory SET reserved_quantity = reserved_quantity + ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?', [amount, stock.id]); await db.run('INSERT INTO inventory_reservations (id, company_id, product_id, project_id, quantity, user_id) VALUES (?, ?, ?, ?, ?, ?)', [reservationId, request.user.company_id, productId, projectId, amount, request.user.id]) }); await audit(request.user, 'RESERVAR', 'ESTOQUE', reservationId, null, request.body); response.status(201).json({ id: reservationId }) } catch (error) { response.status(500).json({ error: 'Não foi possível reservar o estoque.' }) } })
  router.post('/api/products/:id/archive', auth, requireRole(...supplyRoles), async (request, response) => { try { const product = await db.get('SELECT * FROM products WHERE id = ? AND company_id = ?', [request.params.id, request.user.company_id]); if (!product) return response.status(404).json({ error: 'Produto não encontrado.' }); await db.run('UPDATE products SET archived = 1, updated_at = CURRENT_TIMESTAMP WHERE id = ? AND company_id = ?', [product.id, request.user.company_id]); await audit(request.user, 'ARQUIVAR', 'PRODUTOS', product.id, product, { ...product, archived: 1 }); response.json({ ok: true }) } catch (error) { response.status(500).json({ error: 'Não foi possível arquivar o produto.' }) } })

  router.get('/api/purchase-requests/:id/items', auth, async (request, response) => { try { response.json(await db.all('SELECT * FROM purchase_request_items WHERE purchase_request_id = ? AND company_id = ?', [request.params.id, request.user.company_id])) } catch (error) { response.status(500).json({ error: 'Não foi possível listar os itens da solicitação.' }) } })
  router.post('/api/purchase-requests/:id/items', auth, requireRole(...supplyRoles), async (request, response) => { try { const item = { id: id(), ...request.body }; if (!item.description || !item.quantity) return response.status(400).json({ error: 'Produto e quantidade são obrigatórios.' }); await db.run('INSERT INTO purchase_request_items (id, company_id, purchase_request_id, product_id, description, quantity, unit, needed_date) VALUES (?, ?, ?, ?, ?, ?, ?, ?)', [item.id, request.user.company_id, request.params.id, item.product_id || null, item.description, Number(item.quantity), item.unit || 'UN', item.needed_date || null]); response.status(201).json(item) } catch (error) { response.status(500).json({ error: 'Não foi possível adicionar o item.' }) } })
  router.get('/api/purchase-orders/:id/items', auth, async (request, response) => { try { response.json(await db.all('SELECT * FROM purchase_order_items WHERE purchase_order_id = ? AND company_id = ?', [request.params.id, request.user.company_id])) } catch (error) { response.status(500).json({ error: 'Não foi possível listar os itens da ordem.' }) } })
  router.post('/api/purchase-orders/:id/items', auth, requireRole(...supplyRoles), async (request, response) => { try { const order = await db.get('SELECT id FROM purchase_orders WHERE id = ? AND company_id = ?', [request.params.id, request.user.company_id]); if (!order) return response.status(404).json({ error: 'Ordem de compra não encontrada.' }); if (!request.body.description || !request.body.quantity) return response.status(400).json({ error: 'Descrição e quantidade são obrigatórias.' }); const item = { id: id(), ...request.body }; await db.run('INSERT INTO purchase_order_items (id, company_id, purchase_order_id, product_id, description, quantity, unit_price) VALUES (?, ?, ?, ?, ?, ?, ?)', [item.id, request.user.company_id, order.id, item.product_id || null, item.description, Number(item.quantity), Number(item.unit_price || 0)]); response.status(201).json(item) } catch (error) { response.status(500).json({ error: 'Não foi possível adicionar o item à ordem.' }) } })

  router.post('/api/purchase-requests/:id/approve', auth, requireRole(...supplyRoles), async (request, response) => { try { const quotation = await db.get('SELECT * FROM quotations WHERE id = ? AND company_id = ? AND status = ?', [request.body.quotation_id, request.user.company_id, 'APROVADA']); const purchaseRequest = await db.get('SELECT * FROM purchase_requests WHERE id = ? AND company_id = ?', [request.params.id, request.user.company_id]); if (!purchaseRequest || !quotation) return response.status(404).json({ error: 'Solicitação ou cotação aprovada não encontrada.' }); const items = await db.all('SELECT * FROM purchase_request_items WHERE purchase_request_id = ? AND company_id = ?', [purchaseRequest.id, request.user.company_id]); const orderId = id(); await db.transaction(async () => { await db.run('UPDATE purchase_requests SET status = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?', ['APROVADA', purchaseRequest.id]); await db.run('UPDATE quotations SET status = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?', ['SELECIONADA', quotation.id]); await db.run('INSERT INTO purchase_orders (id, company_id, number, supplier_id, project_id, status, total) VALUES (?, ?, ?, ?, ?, ?, ?)', [orderId, request.user.company_id, `OC-${Date.now().toString().slice(-6)}`, quotation.supplier_id, purchaseRequest.project_id, 'ABERTA', quotation.total]); for (const item of items) await db.run('INSERT INTO purchase_order_items (id, company_id, purchase_order_id, product_id, description, quantity, unit_price) VALUES (?, ?, ?, ?, ?, ?, ?)', [id(), request.user.company_id, orderId, item.product_id, item.description, item.quantity, quotation.unit_price]) }); await audit(request.user, 'APROVAR', 'COMPRAS', orderId, purchaseRequest, { orderId, quotationId: quotation.id }); response.status(201).json({ id: orderId, status: 'ABERTA' }) } catch (error) { response.status(500).json({ error: 'Não foi possível aprovar a cotação.' }) } })
  router.get('/api/quotations/compare/:requestId', auth, async (request, response) => { try { response.json(await db.all('SELECT q.*, s.trade_name AS supplier_name, s.legal_name FROM quotations q LEFT JOIN suppliers s ON s.id = q.supplier_id WHERE q.purchase_request_id = ? AND q.company_id = ? ORDER BY q.total ASC', [request.params.requestId, request.user.company_id])) } catch (error) { response.status(500).json({ error: 'Não foi possível comparar cotações.' }) } })
  router.post('/api/quotations/:id/select', auth, requireRole(...supplyRoles), async (request, response) => { try { const quotation = await db.get('SELECT * FROM quotations WHERE id = ? AND company_id = ?', [request.params.id, request.user.company_id]); if (!quotation) return response.status(404).json({ error: 'Cotação não encontrada.' }); const purchaseRequest = await db.get('SELECT * FROM purchase_requests WHERE id = ? AND company_id = ?', [quotation.purchase_request_id, request.user.company_id]); const items = await db.all('SELECT * FROM purchase_request_items WHERE purchase_request_id = ? AND company_id = ?', [quotation.purchase_request_id, request.user.company_id]); const orderId = id(); await db.transaction(async () => { await db.run('UPDATE quotations SET status = CASE WHEN id = ? THEN ? ELSE ? END, updated_at = CURRENT_TIMESTAMP WHERE purchase_request_id = ? AND company_id = ?', [quotation.id, 'SELECIONADA', 'RECUSADA', quotation.purchase_request_id, request.user.company_id]); await db.run('UPDATE purchase_requests SET status = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?', ['APROVADA', purchaseRequest.id]); await db.run('INSERT INTO purchase_orders (id, company_id, number, supplier_id, project_id, status, total) VALUES (?, ?, ?, ?, ?, ?, ?)', [orderId, request.user.company_id, `OC-${Date.now().toString().slice(-6)}`, quotation.supplier_id, purchaseRequest.project_id, 'ABERTA', quotation.total]); for (const item of items) await db.run('INSERT INTO purchase_order_items (id, company_id, purchase_order_id, product_id, description, quantity, unit_price) VALUES (?, ?, ?, ?, ?, ?, ?)', [id(), request.user.company_id, orderId, item.product_id, item.description, item.quantity, quotation.unit_price]) }); await audit(request.user, 'APROVAR', 'COTACOES', quotation.id, null, { quotationId: quotation.id, orderId }); response.status(201).json({ orderId, status: 'ABERTA' }) } catch (error) { response.status(500).json({ error: 'Não foi possível selecionar a cotação.' }) } })

  router.post('/api/purchase-orders/:id/receive', auth, requireRole(...supplyRoles), async (request, response) => { try { const order = await db.get('SELECT * FROM purchase_orders WHERE id = ? AND company_id = ?', [request.params.id, request.user.company_id]); if (!order) return response.status(404).json({ error: 'Ordem de compra não encontrada.' }); if (order.status === 'RECEBIDA') return response.status(409).json({ error: 'Esta ordem já foi recebida.' }); const items = await db.all('SELECT * FROM purchase_order_items WHERE purchase_order_id = ? AND company_id = ?', [order.id, request.user.company_id]); await db.transaction(async () => { for (const item of items) { const stock = await db.get('SELECT * FROM inventory WHERE company_id = ? AND product_id = ? AND project_id IS NULL', [request.user.company_id, item.product_id]); if (stock) await db.run('UPDATE inventory SET quantity = quantity + ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?', [item.quantity, stock.id]); else await db.run('INSERT INTO inventory (id, company_id, product_id, quantity) VALUES (?, ?, ?, ?)', [id(), request.user.company_id, item.product_id, item.quantity]); await db.run('INSERT INTO inventory_movements (id, company_id, product_id, type, quantity, user_id, note) VALUES (?, ?, ?, ?, ?, ?, ?)', [id(), request.user.company_id, item.product_id, 'ENTRADA', item.quantity, request.user.id, `Recebimento da ordem ${order.id}`]); await db.run('UPDATE purchase_order_items SET received_quantity = quantity, updated_at = CURRENT_TIMESTAMP WHERE id = ?', [item.id]) } await db.run('UPDATE purchase_orders SET status = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?', ['RECEBIDA', order.id]) }); await audit(request.user, 'RECEBER', 'COMPRAS', order.id, order, { ...order, status: 'RECEBIDA' }); response.json({ ok: true, status: 'RECEBIDA' }) } catch (error) { response.status(500).json({ error: 'Não foi possível receber a ordem de compra.' }) } })

  router.post('/api/accounts-payable/:id/pay', auth, requireRole(...financeRoles), async (request, response) => { try { const account = await db.get('SELECT * FROM accounts_payable WHERE id = ? AND company_id = ?', [request.params.id, request.user.company_id]); if (!account) return response.status(404).json({ error: 'Conta a pagar não encontrada.' }); if (account.status === 'PAGA') return response.status(409).json({ error: 'Esta conta já foi paga.' }); const paidAmount = Number(request.body.amount || account.amount); await db.transaction(async () => { await db.run('UPDATE accounts_payable SET status = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? AND company_id = ?', ['PAGA', account.id, request.user.company_id]); await db.run('INSERT INTO financial_transactions (id, company_id, project_id, user_id, description, category, amount, type, status, transaction_date) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', [id(), request.user.company_id, account.project_id, request.user.id, `Pagamento: ${account.description}`, 'CONTAS_A_PAGAR', paidAmount, 'SAIDA', 'CONFIRMADA', request.body.paid_date || new Date().toISOString().slice(0, 10)]) }); await audit(request.user, 'PAGAR', 'FINANCEIRO', account.id, account, { ...account, status: 'PAGA', paidAmount }); response.json({ ok: true, status: 'PAGA' }) } catch (error) { response.status(500).json({ error: 'Não foi possível registrar o pagamento.' }) } })
  router.post('/api/accounts-receivable/:id/receive', auth, requireRole(...financeRoles), async (request, response) => { try { const account = await db.get('SELECT * FROM accounts_receivable WHERE id = ? AND company_id = ?', [request.params.id, request.user.company_id]); if (!account) return response.status(404).json({ error: 'Conta a receber não encontrada.' }); if (account.status === 'RECEBIDA') return response.status(409).json({ error: 'Esta conta já foi recebida.' }); const receivedAmount = Number(request.body.amount || account.amount); await db.transaction(async () => { await db.run('UPDATE accounts_receivable SET status = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? AND company_id = ?', ['RECEBIDA', account.id, request.user.company_id]); await db.run('INSERT INTO financial_transactions (id, company_id, project_id, user_id, description, category, amount, type, status, transaction_date) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', [id(), request.user.company_id, account.project_id, request.user.id, `Recebimento: ${account.description}`, 'CONTAS_A_RECEBER', receivedAmount, 'ENTRADA', 'CONFIRMADA', request.body.received_date || new Date().toISOString().slice(0, 10)]) }); await audit(request.user, 'RECEBER', 'FINANCEIRO', account.id, account, { ...account, status: 'RECEBIDA', receivedAmount }); response.json({ ok: true, status: 'RECEBIDA' }) } catch (error) { response.status(500).json({ error: 'Não foi possível registrar o recebimento.' }) } })

  router.get('/api/maintenance', auth, async (request, response) => { try { const pagination = paginationFor(request); const params = [request.user.company_id]; const where = ['m.company_id = ?']; if (request.query.equipment_id) { where.push('m.equipment_id = ?'); params.push(request.query.equipment_id) } if (request.query.status) { where.push('m.status = ?'); params.push(request.query.status) } if (request.query.type) { where.push('m.type = ?'); params.push(request.query.type) } if (request.query.from) { where.push('date(m.scheduled_at) >= date(?)'); params.push(request.query.from) } if (request.query.to) { where.push('date(m.scheduled_at) <= date(?)'); params.push(request.query.to) } const count = await db.get(`SELECT COUNT(*) AS total FROM maintenance_records m JOIN equipment e ON e.id = m.equipment_id WHERE ${where.join(' AND ')}`, params); const rows = await db.all(`SELECT m.*, e.name AS equipment_name FROM maintenance_records m JOIN equipment e ON e.id = m.equipment_id WHERE ${where.join(' AND ')} ORDER BY m.created_at DESC LIMIT ? OFFSET ?`, [...params, pagination.pageSize, pagination.offset]); response.json(pagination.requested ? { data: rows, pagination: { page: pagination.page, pageSize: pagination.pageSize, total: count.total, totalPages: Math.ceil(count.total / pagination.pageSize) } } : rows) } catch (error) { response.status(500).json({ error: 'Não foi possível listar manutenções.' }) } })
  router.get('/api/maintenance/:equipmentId', auth, async (request, response) => { try { response.json(await db.all('SELECT m.*, e.name AS equipment_name FROM maintenance_records m JOIN equipment e ON e.id = m.equipment_id WHERE m.equipment_id = ? AND m.company_id = ? ORDER BY m.created_at DESC', [request.params.equipmentId, request.user.company_id])) } catch (error) { response.status(500).json({ error: 'Não foi possível listar manutenções.' }) } })
  router.post('/api/maintenance', auth, requireRole(...writeRoles), async (request, response) => { try { const record = { id: id(), ...request.body }; if (!record.equipment_id || !record.type || !record.description) return response.status(400).json({ error: 'Equipamento, tipo e descrição são obrigatórios.' }); await db.run('INSERT INTO maintenance_records (id, company_id, equipment_id, type, description, opened_at, scheduled_at, completed_at, responsible, supplier, cost, horometer, mileage, parts_used, labor_cost, next_due_at, observations, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', [record.id, request.user.company_id, record.equipment_id, record.type, record.description, record.opened_at || new Date().toISOString().slice(0, 10), record.scheduled_at, record.completed_at, record.responsible, record.supplier, record.cost || 0, record.horometer || null, record.mileage || null, record.parts_used, record.labor_cost || 0, record.next_due_at, record.observations, record.status || 'AGENDADA']); await audit(request.user, 'CRIAR', 'MANUTENCAO', record.id, null, record); response.status(201).json(record) } catch (error) { response.status(500).json({ error: 'Não foi possível registrar manutenção.' }) } })
  router.put('/api/maintenance/:id', auth, requireRole(...writeRoles), async (request, response) => { try { const previous = await db.get('SELECT * FROM maintenance_records WHERE id = ? AND company_id = ?', [request.params.id, request.user.company_id]); if (!previous) return response.status(404).json({ error: 'Manutenção não encontrada.' }); const next = { ...previous, ...request.body }; await db.run('UPDATE maintenance_records SET type = ?, description = ?, scheduled_at = ?, completed_at = ?, responsible = ?, supplier = ?, cost = ?, horometer = ?, mileage = ?, parts_used = ?, labor_cost = ?, next_due_at = ?, observations = ?, status = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? AND company_id = ?', [next.type, next.description, next.scheduled_at, next.completed_at, next.responsible, next.supplier, next.cost || 0, next.horometer, next.mileage, next.parts_used, next.labor_cost || 0, next.next_due_at, next.observations, next.status, request.params.id, request.user.company_id]); const updated = await db.get('SELECT * FROM maintenance_records WHERE id = ? AND company_id = ?', [request.params.id, request.user.company_id]); await audit(request.user, 'EDITAR', 'MANUTENCAO', request.params.id, previous, updated); response.json(updated) } catch (error) { response.status(500).json({ error: 'Não foi possível editar manutenção.' }) } })
  router.delete('/api/maintenance/:id', auth, requireRole(...writeRoles), async (request, response) => { try { const previous = await db.get('SELECT * FROM maintenance_records WHERE id = ? AND company_id = ?', [request.params.id, request.user.company_id]); if (!previous) return response.status(404).json({ error: 'Manutenção não encontrada.' }); await db.run('UPDATE maintenance_records SET status = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? AND company_id = ?', ['CANCELADA', request.params.id, request.user.company_id]); await audit(request.user, 'CANCELAR', 'MANUTENCAO', request.params.id, previous, { ...previous, status: 'CANCELADA' }); response.status(204).end() } catch (error) { response.status(500).json({ error: 'Não foi possível cancelar manutenção.' }) } })
  return router
}

module.exports = createCrudRoutes
