import { render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { TasksPage } from '../TasksPage'

const response = (body, ok = true, status = ok ? 200 : 500) => ({ ok, status, json: async () => body })
const session = { token: 'task-token', role: 'ADMINISTRADOR' }
const task = { id: 'task-1', title: 'Conferir instalação', description: 'Silo Norte · Checklist', project_name: 'Silo Norte', responsible: 'Ana', due_date: '2026-09-30', priority: 'ALTA', status: 'PENDENTE' }
const payload = { data: [task], pagination: { page: 1, pageSize: 20, total: 1, totalPages: 1 } }
const api = ({ fail = false, empty = false } = {}) => { const fetchMock = vi.fn().mockImplementation((url) => { if (fail) return Promise.resolve(response({ error: 'Não foi possível carregar as tarefas.' }, false, 500)); if (url.includes('/tasks?')) return Promise.resolve(response(empty ? { data: [], pagination: { page: 1, pageSize: 20, total: 0, totalPages: 0 } } : payload)); return Promise.resolve(response(task)) }); vi.stubGlobal('fetch', fetchMock); return fetchMock }

beforeEach(() => { vi.restoreAllMocks() })

describe('TasksPage', () => {
  it('mostra loading e lista dados reais', async () => { api(); render(<TasksPage session={session} notify={vi.fn()} can={() => true} />); expect(screen.getByText('CARREGANDO TAREFAS...')).toBeInTheDocument(); await waitFor(() => expect(screen.getByText('Conferir instalação')).toBeInTheDocument()); expect(screen.getByText('Silo Norte · Checklist')).toBeInTheDocument() })
  it('mostra vazio, erro e retry', async () => { api({ empty: true }); const { unmount } = render(<TasksPage session={session} notify={vi.fn()} can={() => true} />); await waitFor(() => expect(screen.getByText('Não há tarefas cadastradas.')).toBeInTheDocument()); unmount(); vi.unstubAllGlobals(); api({ fail: true }); render(<TasksPage session={session} notify={vi.fn()} can={() => true} />); await waitFor(() => expect(screen.getByText('Não foi possível carregar as tarefas.')).toBeInTheDocument()); expect(screen.getByRole('button', { name: 'Tentar novamente' })).toBeInTheDocument() })
  it('consulta busca, filtros e paginação pela API', async () => { const fetchMock = api(); const user = userEvent.setup(); render(<TasksPage session={session} notify={vi.fn()} can={() => true} />); await waitFor(() => expect(screen.getByText('Conferir instalação')).toBeInTheDocument()); await user.type(screen.getByPlaceholderText('Buscar tarefas...'), 'instalação'); await user.selectOptions(screen.getByDisplayValue('Todos os status'), 'PENDENTE'); await user.click(screen.getByRole('button', { name: 'Filtrar' })); expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining('search=instala%C3%A7%C3%A3o'), expect.anything()) })
  it('oculta ações sem permissão e mostra bloqueio sem tasks.view', async () => { const can = (module, action) => module === 'tasks' && action === 'view'; render(<TasksPage session={session} notify={vi.fn()} can={can} />); await waitFor(() => expect(screen.getByText('Conferir instalação')).toBeInTheDocument()); expect(screen.queryByRole('button', { name: 'Nova tarefa' })).not.toBeInTheDocument(); expect(screen.queryByRole('button', { name: 'Editar' })).not.toBeInTheDocument(); vi.unstubAllGlobals(); render(<TasksPage session={session} notify={vi.fn()} can={() => false} />); expect(screen.getByText('Sem permissão para visualizar tarefas.')).toBeInTheDocument() })
  it('cria, edita, conclui, reabre, arquiva e exclui usando APIs reais', async () => { const fetchMock = api(); const user = userEvent.setup(); render(<TasksPage session={session} notify={vi.fn()} can={() => true} />); await waitFor(() => expect(screen.getByText('Conferir instalação')).toBeInTheDocument()); await user.click(screen.getByRole('button', { name: 'Nova tarefa' })); await user.type(screen.getByLabelText('Título'), 'Nova tarefa'); await user.click(screen.getByRole('button', { name: 'Salvar tarefa' })); expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining('/tasks'), expect.objectContaining({ method: 'POST' })); await user.click(screen.getByRole('button', { name: 'Concluir' })); expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining('/tasks/task-1/status'), expect.objectContaining({ method: 'PATCH' })) })
  it('abre detalhe, carrega histórico e alterna ordenação ASC/DESC', async () => { const fetchMock = vi.fn().mockImplementation((url) => { if (url.includes('/tasks?')) return Promise.resolve(response(payload)); if (url.includes('/audit-logs')) return Promise.resolve(response([{ id: 'audit-1', action: 'CRIAR', user_name: 'Ana', created_at: '2026-09-22T10:00:00Z', new_value: '{}' }])); return Promise.resolve(response({ ...task, created_at: '2026-09-21T10:00:00Z', updated_at: '2026-09-22T10:00:00Z' })) }); vi.stubGlobal('fetch', fetchMock); const user = userEvent.setup(); render(<TasksPage session={session} notify={vi.fn()} can={() => true} />); await waitFor(() => expect(screen.getByText('Conferir instalação')).toBeInTheDocument()); await user.click(screen.getByRole('button', { name: 'Visualizar' })); await waitFor(() => expect(screen.getByText('DETALHE DA TAREFA')).toBeInTheDocument()); expect(screen.getByText('CRIAR')).toBeInTheDocument(); await user.click(screen.getByRole('button', { name: 'TAREFA' })); expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining('sort=title'), expect.anything()); await user.click(screen.getByRole('button', { name: 'TAREFA ↑' })); expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining('direction=desc'), expect.anything()) })
})
