import { useCallback, useEffect, useMemo, useState } from 'react'
import { Check, Pencil, Plus, RefreshCw, ShieldCheck, UserRound, X } from 'lucide-react'
import './AppNew.css'

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:3333/api'
const actionLabels = { view: 'Visualizar', create: 'Criar', edit: 'Editar', delete: 'Excluir', archive: 'Arquivar', approve: 'Aprovar', pay: 'Pagar', receive: 'Receber', export: 'Exportar', upload: 'Upload', download: 'Download' }

function AdminPage({ session, notify }) {
  const [tab, setTab] = useState('users')
  const [users, setUsers] = useState([])
  const [roles, setRoles] = useState([])
  const [permissions, setPermissions] = useState([])
  const [rolePermissions, setRolePermissions] = useState([])
  const [audit, setAudit] = useState([])
  const [selectedRole, setSelectedRole] = useState('')
  const [search, setSearch] = useState('')
  const [state, setState] = useState({ loading: true, error: '' })
  const [modal, setModal] = useState(null)
  const headers = useMemo(() => ({ Authorization: `Bearer ${session.token}` }), [session.token])
  const request = useCallback(async (url, options = {}) => { const response = await fetch(`${API_URL}${url}`, { ...options, headers: { ...headers, ...(options.headers || {}) } }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.error || 'Não foi possível concluir a operação.'); return payload }, [headers])
  const load = useCallback(async () => { try { const [userRows, roleRows, permissionRows, auditRows] = await Promise.all([request(`/users?search=${encodeURIComponent(search)}`), request('/roles'), request('/permissions'), request('/access-audit')]); setUsers(userRows); setRoles(roleRows); setPermissions(permissionRows); setAudit(auditRows); const firstRole = selectedRole || roleRows[0]?.id || ''; setSelectedRole(firstRole); if (firstRole) { const roleData = await request(`/roles/${firstRole}/permissions`); setRolePermissions(roleData.permissions || []) } } catch (error) { setState({ loading: false, error: error.message }); return } setState({ loading: false, error: '' }) }, [request, search, selectedRole])
  useEffect(() => { if (session.role !== 'ADMINISTRADOR') return undefined; const timer = window.setTimeout(() => { void load() }, 0); return () => window.clearTimeout(timer) }, [session.role, load])
  const permissionIds = useMemo(() => new Set(rolePermissions.map((permission) => permission.id)), [rolePermissions])
  const modules = [...new Set(permissions.map((permission) => permission.module))]
  async function saveRolePermissions(nextIds) { try { await request(`/roles/${selectedRole}/permissions`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ permission_ids: nextIds }) }); setRolePermissions(permissions.filter((permission) => nextIds.includes(permission.id))); notify('Permissões do perfil atualizadas.'); await load() } catch (error) { setState({ loading: false, error: error.message }) } }
  if (session.role !== 'ADMINISTRADOR') return <><SectionHeading kicker="ADMINISTRAÇÃO" title="Acesso restrito" description="Seu perfil não possui permissão para gerenciar usuários e permissões." /><DataState message="Sem permissão administrativa." /></>
  return <><SectionHeading kicker="ADMINISTRAÇÃO" title="Usuários, perfis e permissões" description="Gerencie o acesso da empresa com as regras reais do Nexora." action={<button className="outline-button" onClick={load}><RefreshCw size={15} /> Atualizar</button>} /><div className="admin-tabs"><button className={tab === 'users' ? 'active' : ''} onClick={() => setTab('users')}><UserRound size={15} /> Usuários</button><button className={tab === 'roles' ? 'active' : ''} onClick={() => setTab('roles')}><ShieldCheck size={15} /> Perfis e matriz</button><button className={tab === 'audit' ? 'active' : ''} onClick={() => setTab('audit')}>Auditoria de acesso</button></div>{state.loading ? <DataState message="CARREGANDO ADMINISTRAÇÃO..." /> : state.error ? <DataState message={state.error} action={<button className="blue-button" onClick={load}>Tentar novamente</button>} /> : tab === 'users' ? <UsersPanel users={users} search={search} setSearch={setSearch} onSearch={load} onCreate={() => setModal({})} onEdit={(user) => setModal(user)} onStatus={async (user) => { try { await request(`/users/${user.id}/status`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status: user.status === 'ATIVO' ? 'INATIVO' : 'ATIVO' }) }); notify('Status do usuário atualizado.'); await load() } catch (error) { setState({ loading: false, error: error.message }) } }} /> : tab === 'roles' ? <RolesPanel roles={roles} selectedRole={selectedRole} setSelectedRole={setSelectedRole} modules={modules} permissions={permissions} permissionIds={permissionIds} onToggle={(permissionId) => saveRolePermissions(permissionIds.has(permissionId) ? [...permissionIds].filter((id) => id !== permissionId) : [...permissionIds, permissionId])} /> : <AuditPanel entries={audit} />}{modal && <UserModal user={modal.id ? modal : null} roles={roles} onClose={() => setModal(null)} onSave={async (data) => { try { if (modal.id) await request(`/users/${modal.id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }); else await request('/users', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }); setModal(null); notify('Usuário salvo com sucesso.'); await load() } catch (error) { setState({ loading: false, error: error.message }) } }} />}</>
}
async function resetUserPassword(user) { const password = window.prompt('Nova senha (mínimo de 8 caracteres):'); if (!password || !window.confirm('Confirmar redefinição de senha?')) return; const session = JSON.parse(localStorage.getItem('nexora-session') || 'null'); const response = await fetch(`${API_URL}/users/${user.id}/reset-password`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${session?.token || ''}` }, body: JSON.stringify({ password }) }); if (!response.ok) { const payload = await response.json(); window.alert(payload.error || 'Não foi possível redefinir a senha.'); throw new Error(payload.error || 'Não foi possível redefinir a senha.') } window.alert('Senha redefinida com sucesso.') }
function UsersPanel({ users, search, setSearch, onSearch, onCreate, onEdit, onStatus }) { return <div className="admin-panel panel"><div className="admin-toolbar"><input className="filter-input" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar usuário por nome ou e-mail" /><button className="outline-button" onClick={onSearch}>Buscar</button><button className="blue-button" onClick={onCreate}><Plus size={15} /> Novo usuário</button></div>{!users.length ? <DataState message="Nenhum usuário encontrado." /> : <div className="table-scroll"><table><thead><tr><th>NOME</th><th>E-MAIL</th><th>PERFIL</th><th>STATUS</th><th>CRIADO EM</th><th /></tr></thead><tbody>{users.map((user) => <tr key={user.id}><td><b>{user.name}</b><small>{user.job_title || 'Sem cargo informado'}</small></td><td>{user.email}</td><td>{user.role_name || 'Sem perfil'}</td><td><em className={`status ${user.status === 'ATIVO' ? 'green' : 'red'}`}>{user.status}</em></td><td>{new Date(user.created_at).toLocaleDateString('pt-BR')}</td><td><div className="row-actions"><button className="table-action" onClick={() => onEdit(user)}><Pencil size={13} /> Editar</button><button className="table-action" onClick={() => resetUserPassword(user).catch(() => {})}>Redefinir senha</button><button className="table-action danger" onClick={() => onStatus(user)}>{user.status === 'ATIVO' ? 'Desativar' : 'Ativar'}</button></div></td></tr>)}</tbody></table></div>}</div> }
function RolesPanel({ roles, selectedRole, setSelectedRole, modules, permissions, permissionIds, onToggle }) { const actions = Object.keys(actionLabels); return <div className="admin-panel panel"><div className="admin-toolbar"><label className="field admin-role-select"><span>Perfil</span><select value={selectedRole} onChange={(event) => setSelectedRole(event.target.value)}>{roles.map((role) => <option key={role.id} value={role.id}>{role.name}</option>)}</select></label><span className="admin-note">A matriz usa somente permissões cadastradas no banco.</span></div><div className="permission-matrix"><table><thead><tr><th>MÓDULO</th>{actions.map((action) => <th key={action}>{actionLabels[action]}</th>)}</tr></thead><tbody>{modules.map((module) => <tr key={module}><td><b>{module}</b></td>{actions.map((action) => { const permission = permissions.find((item) => item.module === module && item.action === action); return <td key={action}>{permission ? <button className={`permission-cell ${permissionIds.has(permission.id) ? 'allowed' : ''}`} aria-label={`${module} ${action}`} onClick={() => onToggle(permission.id)}>{permissionIds.has(permission.id) ? <Check size={14} /> : '—'}</button> : '—'}</td> })}</tr>)}</tbody></table></div></div> }
function AuditPanel({ entries }) { return <div className="admin-panel panel">{!entries.length ? <DataState message="Nenhuma alteração de acesso registrada." /> : <div className="audit-list">{entries.map((entry) => <article className="history-entry" key={entry.id}><time>{new Date(entry.created_at).toLocaleString('pt-BR')}</time><strong>{entry.actor_name || 'Usuário'}</strong><span>{entry.action} · {entry.module} · alvo {entry.record_id || '-'}</span><small>{entry.new_value || ''}</small></article>)}</div>}</div> }
function UserModal({ user, roles, onClose, onSave }) { const value = (field) => user?.[field] || ''; return <div className="modal-layer" onClick={onClose}><form className="modal-card" onClick={(event) => event.stopPropagation()} onSubmit={(event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); onSave(data) }}><button type="button" className="modal-x" onClick={onClose}><X size={18} /></button><span className="section-kicker">USUÁRIOS</span><h2>{user ? 'Editar usuário' : 'Novo usuário'}</h2><div className="form-grid"><Field label="Nome" name="name" defaultValue={value('name')} required /><Field label="E-mail" name="email" type="email" defaultValue={value('email')} required /></div><div className="form-grid"><Field label="Telefone" name="phone" defaultValue={value('phone')} /><Field label="Cargo" name="job_title" defaultValue={value('job_title')} /></div>{!user && <Field label="Senha" name="password" type="password" minLength={8} required />}<label className="field"><span>Perfil</span><select name="role_id" defaultValue={value('role_id') || roles[0]?.id} required>{roles.map((role) => <option key={role.id} value={role.id}>{role.name}</option>)}</select></label><div className="modal-actions"><button type="button" className="outline-button" onClick={onClose}>Cancelar</button><button className="blue-button">Salvar usuário</button></div></form></div> }
function Field({ label, ...props }) { return <label className="field"><span>{label}</span><input required {...props} /></label> }
function SectionHeading({ kicker, title, description, action }) { return <section className="section-heading"><div><span className="section-kicker">{kicker}</span><h1>{title}</h1><p>{description}</p></div>{action}</section> }
function DataState({ message, action }) { return <div className="data-state panel"><p>{message}</p>{action}</div> }

export { AdminPage }
