import { useState } from 'react'
import { Factory, Plus, X } from 'lucide-react'
import './AppNew.css'
import { API_URL } from './apiConfig'


function ProjectsPage({ projects, pagination, onLoad, onNew, onEdit, session }) {
  const [search, setSearch] = useState('')
  const [status, setStatus] = useState('')
  const [detail, setDetail] = useState(null)
  const filter = (event) => { event.preventDefault(); onLoad({ search, status, page: 1 }) }
  async function openDetail(project) { setDetail({ loading: true, error: '' }); try { const response = await fetch(`${API_URL}/projects/${project.id}/overview`, { headers: { Authorization: `Bearer ${session.token}` } }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || 'Não foi possível carregar o projeto.'); setDetail({ loading: false, error: '', ...payload }) } catch (error) { setDetail({ loading: false, error: error.message }) } }
  return <><SectionHeading kicker="GESTÃO DE OBRAS" title="Projetos e obras" description="Tudo que está em execução, em um único lugar." action={<button className="blue-button" onClick={onNew}><Plus size={17} /> Nova Obra</button>} /><form className="filter-bar panel" onSubmit={filter}><label className="search-box"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar projeto" /></label><select className="filter-input" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">Todos os status</option><option>PLANEJAMENTO</option><option>EM_EXECUCAO</option><option>EM_MONTAGEM</option><option>FINALIZADO</option><option>CANCELADO</option></select><button className="outline-button">Filtrar</button></form><div className="page-panel panel"><PanelHeading title={`${pagination?.total || projects.length} obras cadastradas`} subtitle="Atualizado agora" /><div className="table-scroll"><table><thead><tr><th>OBRA / CONTRATANTE</th><th>PROGRESSO</th><th>STATUS</th><th>ENTREGA</th><th /></tr></thead><tbody>{projects.map((project) => <tr key={project.code}><td><div className="project-name"><span className={`project-icon ${project.tone}`}><Factory size={15} /></span><span><button className="table-link" onClick={() => openDetail(project)}>{project.name}</button><small>{project.code} · {project.location}</small></span></div></td><td>{project.progress}%</td><td><em className={`status ${project.tone}`}>{project.status}</em></td><td>{project.due}</td><td><div className="row-actions"><button className="table-action" onClick={() => openDetail(project)}>Ver detalhes</button>{onEdit && <button className="table-action" onClick={() => onEdit(project)}>Editar</button>}</div></td></tr>)}</tbody></table>{!projects.length && <div className="empty">Nenhum projeto encontrado.</div>}</div><Pagination pagination={pagination} onPage={(page) => onLoad({ search, status, page })} /></div>{detail && <ProjectDetail detail={detail} onClose={() => setDetail(null)} />}</>
}
function ProjectDetail({ detail, onClose }) { if (detail.loading) return <div className="modal-layer"><div className="modal-card"><DataState message="CARREGANDO PROJETO..." /></div></div>; if (detail.error) return <div className="modal-layer"><div className="modal-card"><p>{detail.error}</p><button className="outline-button" onClick={onClose}>Fechar</button></div></div>; const { project, tasks, documents, financial, audit } = detail; return <div className="modal-layer" onClick={onClose}><div className="modal-card project-detail" onClick={(event) => event.stopPropagation()}><button className="modal-x" onClick={onClose}><X size={18} /></button><span className="section-kicker">DETALHE DO PROJETO</span><h2>{project.name}</h2><p>{project.description || 'Sem descrição.'}</p><div className="task-detail-grid"><span>Cliente<strong>{project.client_name || 'Sem cliente'}</strong></span><span>Status<strong>{project.status}</strong></span><span>Início<strong>{project.start_date || '-'}</strong></span><span>Entrega<strong>{project.end_date || '-'}</strong></span><span>Valor contratado<strong>R$ {Number(project.contracted_value || 0).toLocaleString('pt-BR')}</strong></span><span>Custo previsto<strong>R$ {Number(project.expected_cost || 0).toLocaleString('pt-BR')}</strong></span><span>Custo atual<strong>R$ {Number(project.actual_cost || 0).toLocaleString('pt-BR')}</strong></span></div><h3>Tarefas ({tasks?.length || 0})</h3>{tasks?.length ? tasks.map((task) => <div className="module-row" key={task.id}><div><b>{task.title}</b><small>{task.status} · {task.responsible || 'Não atribuído'}</small></div></div>) : <DataState message="Não há tarefas relacionadas." />}<h3>Documentos ({documents?.length || 0})</h3>{documents?.length ? documents.map((document) => <div className="module-row" key={document.id}><div><b>{document.name}</b><small>{document.category || 'Outros'} · {document.size || 0} bytes</small></div></div>) : <DataState message="Não há documentos relacionados." />}<h3>Financeiro</h3>{financial ? <div className="module-row"><div><b>Contas a pagar</b><small>{financial.payables?.length || 0} lançamento(s)</small></div></div> : <DataState message="Informações financeiras não disponíveis para este perfil." />}<h3>Histórico</h3>{audit?.length ? audit.map((entry) => <article className="history-entry" key={entry.id}><time>{new Date(entry.created_at).toLocaleString('pt-BR')}</time><strong>{entry.user_name || 'Usuário'}</strong><span>{entry.action}</span></article>) : <DataState message="Não há histórico para este projeto." />}</div></div> }
function PanelHeading({ title, subtitle }) { return <div className="panel-heading"><div><h2>{title}</h2><p>{subtitle}</p></div></div> }
function SectionHeading({ kicker, title, description, action }) { return <section className="section-heading"><div><span className="section-kicker">{kicker}</span><h1>{title}</h1><p>{description}</p></div>{action}</section> }
function DataState({ message, action }) { return <div className="data-state panel"><p>{message}</p>{action}</div> }
function Pagination({ pagination, onPage }) { if (!pagination?.totalPages || pagination.totalPages <= 1) return null; return <div className="pagination"><span>Página {pagination.page} de {pagination.totalPages} · {pagination.total} registros</span><div><button className="outline-button" disabled={pagination.page <= 1} onClick={() => onPage(pagination.page - 1)}>Anterior</button><button className="outline-button" disabled={pagination.page >= pagination.totalPages} onClick={() => onPage(pagination.page + 1)}>Próxima</button></div></div> }

export { ProjectsPage }
